### ISSUE TITLE
Return history

### ISSUE THREAD

**Issue by szhan** [gfairchild/pyHarmonySearch#11]
Hi @gfairchild , I have extended HarmonySearch to return harmony history as well. At the moment, it saves the harmonies after N evaluations, where N is the number of solutions. Do you think that this is useful? If so, I will do a PR. Thanks.

**Comment by gfairchild** [comment]
That could definitely be useful as well! I'm loving your contributions. Please keep them coming.

Note that you hit me with #10 during the work week, and this week in particular has been crazy. I've got the tab open, and I'll review it this weekend.

**Comment by szhan** [comment]
Thanks! No hurry. I will make another PR for the histories.

**Comment by gfairchild** [comment]
Implemented in #10.
