### ISSUE TITLE
Instance of 'ObjectiveFunction' has no '_random_seed' member error

### ISSUE THREAD

**Issue by sushapat** [gfairchild/pyHarmonySearch#14]
I get this error when i run the code
![image](https://user-images.githubusercontent.com/36053910/70230411-46aa8d80-1726-11ea-8531-e1b5d0bb38ac.png)

**Comment by gfairchild** [comment]
It looks like you haven't defined `_random_seed` in your class. You'll need to define that variable if you want to use it like that.

**Comment by gfairchild** [comment]
Were you able to fix this?

**Comment by gfairchild** [comment]
I'm going to go ahead and close this issue. Please let me know if you continue to experience problems.
