### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation in pip installation

### ISSUE THREAD

**Issue by zhanghaocol** [gfairchild/pyHarmonySearch#15]
Hi,
Using pip installed pyHarmonySearch, encountered

>  File "/usr/local/lib/python3.7/site-packages/pyharmonysearch/harmony_search.py", line 120
    self._initialize(initial_harmonies)
                                      ^

> TabError: inconsistent use of tabs and spaces in indentation

**Comment by gfairchild** [comment]
Hm, looking at https://github.com/gfairchild/pyHarmonySearch/blob/master/pyharmonysearch/harmony_search.py, I don't see any tabs. But you're right - looking at the release of 1.4.1 on PyPI, there is indeed a rogue tab. I just fixed  it in 1.4.2, so if you `pip install --upgrade pyHarmonySearch`, it should work now. Can you verify?

Sorry about that! No idea how that happened.

**Comment by gfairchild** [comment]
I'm going to go ahead and close this issue. Please let me know if you continue to experience problems.
