### ISSUE TITLE
The harmony_histories returns a list with all generation as the last generation. 

### ISSUE THREAD

**Issue by xiang3874264** [gfairchild/pyHarmonySearch#16]
I got a harmony_histories contain many generation, but they turn out to be with the same HMS. I considered it might be the last generation.

The code:

https://github.com/gfairchild/pyHarmonySearch/blob/11c57620f8c2295459bbe9ffe9542014ef1f3262/pyharmonysearch/harmony_search.py#L142

I think this part might need a deepcopy?

**Comment by gfairchild** [comment]
Nice, thanks for the issue. I'll poke into this more deeply next week.

**Comment by gfairchild** [comment]
Sorry this took so long to look into, but you're 100% spot on. I'm fixing this now.

**Comment by gfairchild** [comment]
Ok, 1.4.3, which fixes this bug, is now live. Thank you!
