### ISSUE TITLE
Provide initial position

### ISSUE THREAD

**Issue by szhan** [gfairchild/pyHarmonySearch#9]
Hi @gfairchild,

I would like to provide HS an initial position. The present implementation does not provide such an option. I am thinking to modify the run() function to take an initial position. I am thinking to provide it a list of lists (the initial positions, one for each individual), and modify self.initialize(). Any suggestions would be much appreciated.

Thank you very much.

**Comment by gfairchild** [comment]
Your intuition is right; you simply need to override `HarmonySearch._initialize` to create the initial state you desire.

**Comment by szhan** [comment]
Thanks, @gfairchild.

I think I have managed to do this. I just propagate a set of initial harmonies (as a list of lists) from harmony_search() all the way to _initialize(), and then populate _harmony_memory. Would you think this is a useful feature to incorporate into pyHarmonySearch? If so, I would do a PR after some refactoring. Please let me know.

Thanks for creating this resource!

**Comment by gfairchild** [comment]
Actually, I'd love it. That sounds like a nice feature that other people could potentially want. Please send a PR my way!

**Comment by gfairchild** [comment]
Implemented in #10.
